---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
 template:
  metadata:
    name: jenkins
    labels:
      app: jenkins
  spec:
    containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
    restartPolicy: Always
    volumes:
    - name: jenkins-home
      gcePersistentDisk:
          pdName: jenkins-disk
          fsType: ext4
 replicas: 1
 selector:
   matchLabels:
     app: jenkins
---
kind: PersistentDisk
apiVersion: v1
metadata:
  name: jenkins-disk
spec:
  sizeGb: 5
  type: pd-standard
  zone: us-central1-a

