---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
 template:
  metadata:
    name: jenkins
    labels:
      app: jenkins
  spec:
    containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
    # restartPolicy: Always
    volumes:
    - name: jenkins-home
      persistentVolumeClaim:
          claimName: jenkins-pvc
 replicas: 1
 selector:
   matchLabels:
     app: jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP  
      port: 8080
      targetPort: 8080
      name: http
  selector:
    app: jenkins
